version: '2'

services:
  front:
    build: .
    command: npm run dev
    volumes:
      - ./front:/nuxtjs
      # - /nuxtjs/node_modules
    environment:
      HOST: 0.0.0.0
      PORT: 3333
    ports:
      - 3333:3333
